version: '2'
services:
  web:
    build: .
    image: fivestrikes2_rails32_web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: 'development'
    command: bundle exec rails server
